### ISSUE TITLE
Jacoco - Source file ".kt" was not found during generation of report.

### ISSUE THREAD

**Issue by nbentoneves** [nbentoneves/sesame-java#12]
### Resume:
After generating the jacoco report for the .kt files we can't see the code source.

### Print:
<img width="1015" alt="jacocoReport" src="https://user-images.githubusercontent.com/3682693/79135248-f794f900-7da6-11ea-9d3b-d810c8a7fa40.png">

**Comment by avelon1A** [comment]
we can see just configure jacoco  correctly
